import pandas as pd
import matplotlib.pyplot as plt
import os

# Get the directory where this script is located
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# Define paths relative to the script location
# Assumes structure: physi-sim/python/plot_convergence.py
OUTPUT_DIR = os.path.join(SCRIPT_DIR, '../output')
SAVE_DIR = os.path.join(SCRIPT_DIR, '../docs/figures')

# Create figures directory if it doesn't exist
os.makedirs(SAVE_DIR, exist_ok=True)

def generate_comparison_plot():
    try:
        # Load the CSVs generated by your C++ tests
        jacobi = pd.read_csv(os.path.join(OUTPUT_DIR, 'jacobi_convergence.csv'))
        tdma = pd.read_csv(os.path.join(OUTPUT_DIR, 'tdma_convergence.csv'))

        plt.figure(figsize=(10, 6))
        plt.semilogy(jacobi['Iteration'], jacobi['Relative_Error'], label='Jacobi (Point-Iterative)', color='tab:blue', alpha=0.7)
        plt.semilogy(tdma['Iteration'], tdma['Relative_Error'], label='LBL TDMA (Line-Implicit)', color='tab:red', linewidth=2)

        plt.xlabel('Iteration Count')
        plt.ylabel('L-infinity Residual (log scale)')
        plt.title('Numerical Convergence Profile: Jacobi vs. TDMA')
        plt.grid(True, which="both", ls="-", alpha=0.2)
        plt.legend()

        # Save for LaTeX and README
        save_path = os.path.join(SAVE_DIR, 'convergence_comparison.png')
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        print(f"Successfully generated: {save_path}")

    except Exception as e:
        print(f"Could not generate plot: {e}")

if __name__ == "__main__":
    generate_comparison_plot()
